# make sure you define tag index before defining tag coordinates
apriltags: [2, 4, 7]

# the program will look for the tag index first to read each tag coordinate
tag2: [0.527691, 0.951328, 3.553110, -0.0860908, -0.5304828, 0.3275735, 0.777092]
tag4: [-4.481725, -0.078901, 3.897531, 0.4560009, 0.471304, 0.5323045, 0.5353388 ]
tag7: [-1.716379, -0.559175, 3.895554, -0.1103371, -0.6865848, 0.1305297, 0.7066747 ]


# complimentary filter gain. Higher value slower update, less noisy
alpha: 0.95

#   linear.x  (+)      Translate forward
#             (-)      Translate backward
#   linear.y  (+)      Translate to left -> (NEGATIVE gain)
#             (-)      Translate to right
#   linear.z  (+)      Ascend
#             (-)      Descend
#   angular.z (+)      Rotate counter clockwise -> (NEGATIVE gain)
#             (-)      Rotate clockwise

pid_gains: [
  0.50, 0.70, 0,
 -0.50, -0.70, 0,
  0.50, 0.70, 0,
  0.0, 0, 0
]

# set the control loop duration default 30 Hz -> 0.03
dt: 0.03
# set hovering region
goal_thres: 0.2